apiVersion: v1
kind: Service
metadata:
  name: bill-service-container
  #namespace: my-name-space
spec:
  selector:
    app: bill-service-app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9898
      targetPort: 9898