apiVersion: v1
kind: Service
metadata:
  name: ebsconnection-service-container
  #namespace: my-name-space
spec:
  selector:
    app: ebsconnection-service-app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9595
      targetPort: 9595