apiVersion: v1
kind: Service
metadata:
  name: payment-service-container
  #namespace: my-name-space
spec:
  selector:
    app: payment-service-app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9696
      targetPort: 9696