apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  #namespace: my-name-space
spec:
  selector:
    app: user-service-app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9797
      targetPort: 9797