apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service-deployment
  #namespace: my-name-space
  labels:
    app: bill-service-app
   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-service-app
     
  template:
    metadata:
      labels:
        app: bill-service-app   
    spec:
      containers:
      - name: bill-service-app-pod
        image: tk1207/bill-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898

---

apiVersion: v1
kind: Service
metadata:
  name: bill-service-container
  #namespace: my-name-space
spec:
  selector:
    app: bill-service-app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9898
      targetPort: 9898