apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  #namespace: my-name-space
  labels:
    app: user-service-app
   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
     
  template:
    metadata:
      labels:
        app: user-service-app   
    spec:
      containers:
      - name: user-service-app-pod
        image: tk1207/user-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9797

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  #namespace: my-name-space
spec:
  selector:
    app: user-service-app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 9797
      targetPort: 9797